apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zb13rb36t-go
  janus-idp.io/tekton: zb13rb36t-go
  backstage.io/kubernetes-id: zb13rb36t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zb13rb36t-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
